name: dartdoom

packages:
  - packages/**
  - apps/**

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  analyze:
    run: melos exec -- dart analyze --fatal-infos
    description: Run dart analyze in all packages

  fix:
    run: melos exec -- dart fix --apply
    description: Run dart fix in all packages

  format:
    run: melos exec -- dart format .
    description: Format all packages

  test:
    run: melos exec -- flutter test
    packageFilters:
      dirExists: test
    description: Run tests in all packages

  clean:
    run: melos exec -- flutter clean
    description: Clean all packages
