import 'package:doom_core/doom_core.dart';
import 'package:flutter/services.dart';

abstract final class KeyMapping {
  static int? toDoomKey(LogicalKeyboardKey key) {
    return _keyMap[key];
  }

  static final Map<LogicalKeyboardKey, int> _keyMap = {
    LogicalKeyboardKey.arrowUp: DoomKey.upArrow,
    LogicalKeyboardKey.arrowDown: DoomKey.downArrow,
    LogicalKeyboardKey.arrowLeft: DoomKey.leftArrow,
    LogicalKeyboardKey.arrowRight: DoomKey.rightArrow,
    LogicalKeyboardKey.escape: DoomKey.escape,
    LogicalKeyboardKey.enter: DoomKey.enter,
    LogicalKeyboardKey.tab: DoomKey.tab,
    LogicalKeyboardKey.backspace: DoomKey.backspace,
    LogicalKeyboardKey.f1: DoomKey.f1,
    LogicalKeyboardKey.f2: DoomKey.f2,
    LogicalKeyboardKey.f3: DoomKey.f3,
    LogicalKeyboardKey.f4: DoomKey.f4,
    LogicalKeyboardKey.f5: DoomKey.f5,
    LogicalKeyboardKey.f6: DoomKey.f6,
    LogicalKeyboardKey.f7: DoomKey.f7,
    LogicalKeyboardKey.f8: DoomKey.f8,
    LogicalKeyboardKey.f9: DoomKey.f9,
    LogicalKeyboardKey.f10: DoomKey.f10,
    LogicalKeyboardKey.f11: DoomKey.f11,
    LogicalKeyboardKey.f12: DoomKey.f12,
    LogicalKeyboardKey.shiftRight: DoomKey.rshift,
    LogicalKeyboardKey.shiftLeft: DoomKey.rshift,
    LogicalKeyboardKey.controlRight: DoomKey.rctrl,
    LogicalKeyboardKey.controlLeft: DoomKey.rctrl,
    LogicalKeyboardKey.altRight: DoomKey.ralt,
    LogicalKeyboardKey.altLeft: DoomKey.lalt,
    LogicalKeyboardKey.space: 32,
    LogicalKeyboardKey.keyA: 97,
    LogicalKeyboardKey.keyB: 98,
    LogicalKeyboardKey.keyC: 99,
    LogicalKeyboardKey.keyD: 100,
    LogicalKeyboardKey.keyE: 101,
    LogicalKeyboardKey.keyF: 102,
    LogicalKeyboardKey.keyG: 103,
    LogicalKeyboardKey.keyH: 104,
    LogicalKeyboardKey.keyI: 105,
    LogicalKeyboardKey.keyJ: 106,
    LogicalKeyboardKey.keyK: 107,
    LogicalKeyboardKey.keyL: 108,
    LogicalKeyboardKey.keyM: 109,
    LogicalKeyboardKey.keyN: 110,
    LogicalKeyboardKey.keyO: 111,
    LogicalKeyboardKey.keyP: 112,
    LogicalKeyboardKey.keyQ: 113,
    LogicalKeyboardKey.keyR: 114,
    LogicalKeyboardKey.keyS: 115,
    LogicalKeyboardKey.keyT: 116,
    LogicalKeyboardKey.keyU: 117,
    LogicalKeyboardKey.keyV: 118,
    LogicalKeyboardKey.keyW: 119,
    LogicalKeyboardKey.keyX: 120,
    LogicalKeyboardKey.keyY: 121,
    LogicalKeyboardKey.keyZ: 122,
    LogicalKeyboardKey.digit0: 48,
    LogicalKeyboardKey.digit1: 49,
    LogicalKeyboardKey.digit2: 50,
    LogicalKeyboardKey.digit3: 51,
    LogicalKeyboardKey.digit4: 52,
    LogicalKeyboardKey.digit5: 53,
    LogicalKeyboardKey.digit6: 54,
    LogicalKeyboardKey.digit7: 55,
    LogicalKeyboardKey.digit8: 56,
    LogicalKeyboardKey.digit9: 57,
    LogicalKeyboardKey.minus: DoomKey.minus,
    LogicalKeyboardKey.equal: DoomKey.equals,
    LogicalKeyboardKey.comma: 44,
    LogicalKeyboardKey.period: 46,
  };
}
